# Generated by Django 2.2.1 on 2019-06-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='table_employers',
            new_name='Table',
        ),
    ]
